 
# Template script intended to jumpstart the user to run Modus Automatic Test Pattern Generation (ATPG) software.
 
#  Generated by Genus(TM) Synthesis Solution 25.10-p002_1
 
# Modus ATPG Script
 
#-------------------------------------------------------------------------------
# INITIALIZE VARIABLES
#-------------------------------------------------------------------------------
# "set_db workdir" is recommended to be set first to initialize where the Database is to be located
# WORKDIR Tcl variable can be used in the script to reference file locations
set_db workdir ./test_scripts;
set   WORKDIR [get_db workdir]
 
# Configure the database
set_option stdout     summary;                                # Only print a summary for each command to the terminal
                                                          # Logs contain the complete command output
set ::env(CDS_LIC_REPORT) yes
set_db stop_on_severity error;
 
file delete -force $WORKDIR/tbdata;                       # Delete Test Database
file delete -force $WORKDIR/testresults;                  # Delete Test Output Files/Logs
 
 
 
#-------------------------------------------------------------------------------
# BUILD THE LOGIC MODEL
#-------------------------------------------------------------------------------
build_model \
    -cell	 TOP_DATA_WIDTH8_ADDR_WIDTH4_RF_DEPTH16_FIFO_DEPTH2048_FIFO_PTR_WIDTH11 \
    -techlib	 ../../../Library/verilog/typical.v \
    -designsource	 $WORKDIR/TOP_DATA_WIDTH8_ADDR_WIDTH4_RF_DEPTH16_FIFO_DEPTH2048_FIFO_PTR_WIDTH11.test_netlist.v \
    -allowmissingmodules	 yes \
    -messagecounteach	 100 \

 
#-------------------------------------------------------------------------------
# BUILD THE TEST MODEL
#-------------------------------------------------------------------------------
build_testmode \
    -testmode	 FULLSCAN \
    -assignfile	 $WORKDIR/TOP_DATA_WIDTH8_ADDR_WIDTH4_RF_DEPTH16_FIFO_DEPTH2048_FIFO_PTR_WIDTH11.FULLSCAN.pinassign \
    -modedef	 FULLSCAN \
 
 
#-------------------------------------------------------------------------------
# REPORT THE TEST MODEL
#-------------------------------------------------------------------------------
report_test_structures \
    -testmode	 FULLSCAN \
    -reportscanchain	 all \
 
 
#-------------------------------------------------------------------------------
# VERIFY THE TEST MODEL
#-------------------------------------------------------------------------------
verify_test_structures \
    -messagecount	 TSV-016=10,TSV-024=10,TSV-315=10,TSV-027=10 \
    -testmode	 FULLSCAN \
 
 
#-------------------------------------------------------------------------------
# BUILD THE FAULT MODEL
#-------------------------------------------------------------------------------
build_faultmodel \
    -includedynamic	 no \
 
 
#-------------------------------------------------------------------------------
# ATPG - TEST GENERATION
#-------------------------------------------------------------------------------
create_logic_tests \
    -experiment	 TOP_DATA_WIDTH8_ADDR_WIDTH4_RF_DEPTH16_FIFO_DEPTH2048_FIFO_PTR_WIDTH11_atpg \
    -testmode	 FULLSCAN \


#-------------------------------------------------------------------------------
# ATPG - Report the Scan and Capture Switching
#-------------------------------------------------------------------------------
set env(THM_TESTBENCH_NAME) yes
#-------------------------------------------------------------------------------
# ATPG - Create TPI File For Untested Faults
#-------------------------------------------------------------------------------
analyze_deterministic_testpoints \
    -testmode	 FULLSCAN \
    -inexperiment	 TOP_DATA_WIDTH8_ADDR_WIDTH4_RF_DEPTH16_FIFO_DEPTH2048_FIFO_PTR_WIDTH11_atpg


exec ln -s -f ./testresults/TestPointInsertion.FULLSCAN.dfa $WORKDIR/TOP_DATA_WIDTH8_ADDR_WIDTH4_RF_DEPTH16_FIFO_DEPTH2048_FIFO_PTR_WIDTH11.dfa.tpfile
 
#-------------------------------------------------------------------------------
# ATPG - Save Experiment to the Master Database for the Testmode
#-------------------------------------------------------------------------------
commit_tests \
    -inexperiment	 TOP_DATA_WIDTH8_ADDR_WIDTH4_RF_DEPTH16_FIFO_DEPTH2048_FIFO_PTR_WIDTH11_atpg \
    -testmode	 FULLSCAN 


exit
