
//input ports
add mapped point RST_N RST_N -type PI PI
add mapped point UART_CLK UART_CLK -type PI PI
add mapped point REF_CLK REF_CLK -type PI PI
add mapped point UART_RX_IN UART_RX_IN -type PI PI

//output ports
add mapped point UART_TX_O UART_TX_O -type PO PO
add mapped point parity_error parity_error -type PO PO
add mapped point framing_error framing_error -type PO PO

//inout ports




//Sequential Pins
add mapped point U0_ALU_16B/ALU_OUT[0]/q U0_ALU_16B/ALU_OUT_reg[0]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[1]/q U0_ALU_16B/ALU_OUT_reg[1]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[2]/q U0_ALU_16B/ALU_OUT_reg[2]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[3]/q U0_ALU_16B/ALU_OUT_reg[3]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[4]/q U0_ALU_16B/ALU_OUT_reg[4]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[5]/q U0_ALU_16B/ALU_OUT_reg[5]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[6]/q U0_ALU_16B/ALU_OUT_reg[6]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[7]/q U0_ALU_16B/ALU_OUT_reg[7]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[8]/q U0_ALU_16B/ALU_OUT_reg[8]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[9]/q U0_ALU_16B/ALU_OUT_reg[9]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[10]/q U0_ALU_16B/ALU_OUT_reg[10]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[11]/q U0_ALU_16B/ALU_OUT_reg[11]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[12]/q U0_ALU_16B/ALU_OUT_reg[12]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[13]/q U0_ALU_16B/ALU_OUT_reg[13]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[14]/q U0_ALU_16B/ALU_OUT_reg[14]/Q -type DFF DFF
add mapped point U0_ALU_16B/ALU_OUT[15]/q U0_ALU_16B/ALU_OUT_reg[15]/Q -type DFF DFF
add mapped point U0_ALU_16B/OUT_VALID/q U0_ALU_16B/OUT_VALID_reg/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[6][0]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[6][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[0][1]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[0][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[1][1]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[1][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[1][2]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[1][2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[5][0]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[5][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[5][1]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[5][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[5][2]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[5][2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[5][3]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[5][3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[1][3]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[1][3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[5][4]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[5][4]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[5][5]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[5][5]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[1][4]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[1][4]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[5][6]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[5][6]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[5][7]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[5][7]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[1][5]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[1][5]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[1][6]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[1][6]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[0][0]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[0][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[6][1]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[6][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[6][2]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[6][2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[1][7]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[1][7]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[6][3]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[6][3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[6][4]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[6][4]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[2][0]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[2][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[6][5]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[6][5]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[6][6]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[6][6]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[2][1]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[2][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[2][2]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[2][2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[6][7]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[6][7]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[7][0]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[7][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[7][1]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[7][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[7][2]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[7][2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[2][3]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[2][3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[3][4]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[3][4]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[7][4]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[7][4]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[2][4]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[2][4]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[7][5]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[7][5]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[7][6]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[7][6]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[2][5]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[2][5]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[2][6]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[2][6]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[7][7]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[7][7]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[2][7]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[2][7]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[0][2]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[0][2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[0][3]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[0][3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[3][0]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[3][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[3][1]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[3][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[3][2]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[3][2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[3][3]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[3][3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[0][4]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[0][4]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[7][3]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[7][3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[3][5]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[3][5]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[0][5]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[0][5]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[3][6]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[3][6]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[3][7]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[3][7]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[0][6]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[0][6]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[0][7]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[0][7]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[4][0]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[4][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[4][1]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[4][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[4][2]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[4][2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[4][3]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[4][3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[1][0]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[1][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[4][4]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[4][4]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[4][5]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[4][5]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[4][6]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[4][6]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_mem/FIFO_MEM[4][7]/q U0_Async_fifo/u_fifo_mem/FIFO_MEM_reg[4][7]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_rd/gray_rd_ptr[2]/q U0_Async_fifo/u_fifo_rd/gray_rd_ptr_reg[2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_rd/gray_rd_ptr[1]/q U0_Async_fifo/u_fifo_rd/gray_rd_ptr_reg[1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_rd/gray_rd_ptr[3]/q U0_Async_fifo/u_fifo_rd/gray_rd_ptr_reg[3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_rd/rd_ptr[3]/q U0_Async_fifo/u_fifo_rd/rd_ptr_reg[3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_rd/rd_ptr[2]/q U0_Async_fifo/u_fifo_rd/rd_ptr_reg[2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_rd/rd_ptr[1]/q U0_Async_fifo/u_fifo_rd/rd_ptr_reg[1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_rd/gray_rd_ptr[0]/q U0_Async_fifo/u_fifo_rd/gray_rd_ptr_reg[0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_rd/rd_ptr[0]/q U0_Async_fifo/u_fifo_rd/rd_ptr_reg[0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_wr/gray_w_ptr[2]/q U0_Async_fifo/u_fifo_wr/gray_w_ptr_reg[2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_wr/gray_w_ptr[1]/q U0_Async_fifo/u_fifo_wr/gray_w_ptr_reg[1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_wr/gray_w_ptr[3]/q U0_Async_fifo/u_fifo_wr/gray_w_ptr_reg[3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_wr/w_ptr[3]/q U0_Async_fifo/u_fifo_wr/w_ptr_reg[3]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_wr/w_ptr[2]/q U0_Async_fifo/u_fifo_wr/w_ptr_reg[2]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_wr/w_ptr[1]/q U0_Async_fifo/u_fifo_wr/w_ptr_reg[1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_wr/gray_w_ptr[0]/q U0_Async_fifo/u_fifo_wr/gray_w_ptr_reg[0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_fifo_wr/w_ptr[0]/q U0_Async_fifo/u_fifo_wr/w_ptr_reg[0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_r2w_sync/sync_reg[3][1]/q U0_Async_fifo/u_r2w_sync/sync_reg_reg[3][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_r2w_sync/sync_reg[2][1]/q U0_Async_fifo/u_r2w_sync/sync_reg_reg[2][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_r2w_sync/sync_reg[0][1]/q U0_Async_fifo/u_r2w_sync/sync_reg_reg[0][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_r2w_sync/sync_reg[1][1]/q U0_Async_fifo/u_r2w_sync/sync_reg_reg[1][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_r2w_sync/sync_reg[3][0]/q U0_Async_fifo/u_r2w_sync/sync_reg_reg[3][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_r2w_sync/sync_reg[2][0]/q U0_Async_fifo/u_r2w_sync/sync_reg_reg[2][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_r2w_sync/sync_reg[1][0]/q U0_Async_fifo/u_r2w_sync/sync_reg_reg[1][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_r2w_sync/sync_reg[0][0]/q U0_Async_fifo/u_r2w_sync/sync_reg_reg[0][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_w2r_sync/sync_reg[0][1]/q U0_Async_fifo/u_w2r_sync/sync_reg_reg[0][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_w2r_sync/sync_reg[1][1]/q U0_Async_fifo/u_w2r_sync/sync_reg_reg[1][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_w2r_sync/sync_reg[2][1]/q U0_Async_fifo/u_w2r_sync/sync_reg_reg[2][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_w2r_sync/sync_reg[3][1]/q U0_Async_fifo/u_w2r_sync/sync_reg_reg[3][1]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_w2r_sync/sync_reg[1][0]/q U0_Async_fifo/u_w2r_sync/sync_reg_reg[1][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_w2r_sync/sync_reg[2][0]/q U0_Async_fifo/u_w2r_sync/sync_reg_reg[2][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_w2r_sync/sync_reg[3][0]/q U0_Async_fifo/u_w2r_sync/sync_reg_reg[3][0]/Q -type DFF DFF
add mapped point U0_Async_fifo/u_w2r_sync/sync_reg[0][0]/q U0_Async_fifo/u_w2r_sync/sync_reg_reg[0][0]/Q -type DFF DFF
add mapped point U0_CLK_GATE/U0_TLATNCAX12M/ECK U0_CLK_GATE/U0_TLATNCAX12M/ECK -type DLAT DLAT
add mapped point U0_DATA_SYNC/enable_pulse/q U0_DATA_SYNC/enable_pulse_reg/Q -type DFF DFF
add mapped point U0_DATA_SYNC/enable_flop/q U0_DATA_SYNC/enable_flop_reg/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_reg[1]/q U0_DATA_SYNC/sync_reg_reg[1]/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_reg[0]/q U0_DATA_SYNC/sync_reg_reg[0]/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_bus[3]/q U0_DATA_SYNC/sync_bus_reg[3]/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_bus[2]/q U0_DATA_SYNC/sync_bus_reg[2]/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_bus[0]/q U0_DATA_SYNC/sync_bus_reg[0]/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_bus[4]/q U0_DATA_SYNC/sync_bus_reg[4]/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_bus[6]/q U0_DATA_SYNC/sync_bus_reg[6]/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_bus[1]/q U0_DATA_SYNC/sync_bus_reg[1]/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_bus[5]/q U0_DATA_SYNC/sync_bus_reg[5]/Q -type DFF DFF
add mapped point U0_DATA_SYNC/sync_bus[7]/q U0_DATA_SYNC/sync_bus_reg[7]/Q -type DFF DFF
add mapped point U0_Integer_Clock_Divider_TX/counter[6]/q U0_Integer_Clock_Divider_TX/counter_reg[6]/Q -type DFF DFF
add mapped point U0_Integer_Clock_Divider_TX/counter[5]/q U0_Integer_Clock_Divider_TX/counter_reg[5]/Q -type DFF DFF
add mapped point U0_Integer_Clock_Divider_TX/gen_clk/q U0_Integer_Clock_Divider_TX/gen_clk_reg/Q -type DFF DFF
add mapped point U0_Integer_Clock_Divider_TX/counter[1]/q U0_Integer_Clock_Divider_TX/counter_reg[1]/Q -type DFF DFF
add mapped point U0_Integer_Clock_Divider_TX/counter[2]/q U0_Integer_Clock_Divider_TX/counter_reg[2]/Q -type DFF DFF
add mapped point U0_Integer_Clock_Divider_TX/counter[0]/q U0_Integer_Clock_Divider_TX/counter_reg[0]/Q -type DFF DFF
add mapped point U0_Integer_Clock_Divider_TX/counter[4]/q U0_Integer_Clock_Divider_TX/counter_reg[4]/Q -type DFF DFF
add mapped point U0_Integer_Clock_Divider_TX/counter[3]/q U0_Integer_Clock_Divider_TX/counter_reg[3]/Q -type DFF DFF
add mapped point U0_PULSE_GEN/pls_flop/q U0_PULSE_GEN/pls_flop_reg/Q -type DFF DFF
add mapped point U0_PULSE_GEN/rcv_flop/q U0_PULSE_GEN/rcv_flop_reg/Q -type DFF DFF
add mapped point U0_RST_SYNC_REF/sync_reg[1]/q U0_RST_SYNC_REF/sync_reg_reg[1]/Q -type DFF DFF
add mapped point U0_RST_SYNC_REF/sync_reg[0]/q U0_RST_SYNC_REF/sync_reg_reg[0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[0][0]/q U0_Register_File/Memory_reg[0][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[0][1]/q U0_Register_File/Memory_reg[0][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[0][2]/q U0_Register_File/Memory_reg[0][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[0][3]/q U0_Register_File/Memory_reg[0][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[0][4]/q U0_Register_File/Memory_reg[0][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[0][5]/q U0_Register_File/Memory_reg[0][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[0][6]/q U0_Register_File/Memory_reg[0][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[0][7]/q U0_Register_File/Memory_reg[0][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[1][0]/q U0_Register_File/Memory_reg[1][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[1][1]/q U0_Register_File/Memory_reg[1][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[1][2]/q U0_Register_File/Memory_reg[1][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[1][3]/q U0_Register_File/Memory_reg[1][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[1][4]/q U0_Register_File/Memory_reg[1][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[1][5]/q U0_Register_File/Memory_reg[1][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[1][6]/q U0_Register_File/Memory_reg[1][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[1][7]/q U0_Register_File/Memory_reg[1][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[2][0]/q U0_Register_File/Memory_reg[2][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[2][1]/q U0_Register_File/Memory_reg[2][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[2][2]/q U0_Register_File/Memory_reg[2][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[2][3]/q U0_Register_File/Memory_reg[2][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[2][4]/q U0_Register_File/Memory_reg[2][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[2][5]/q U0_Register_File/Memory_reg[2][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[2][6]/q U0_Register_File/Memory_reg[2][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[2][7]/q U0_Register_File/Memory_reg[2][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[3][0]/q U0_Register_File/Memory_reg[3][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[3][1]/q U0_Register_File/Memory_reg[3][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[3][2]/q U0_Register_File/Memory_reg[3][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[3][3]/q U0_Register_File/Memory_reg[3][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[3][4]/q U0_Register_File/Memory_reg[3][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[3][5]/q U0_Register_File/Memory_reg[3][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[3][6]/q U0_Register_File/Memory_reg[3][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[3][7]/q U0_Register_File/Memory_reg[3][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[4][0]/q U0_Register_File/Memory_reg[4][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[4][1]/q U0_Register_File/Memory_reg[4][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[4][2]/q U0_Register_File/Memory_reg[4][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[4][3]/q U0_Register_File/Memory_reg[4][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[4][4]/q U0_Register_File/Memory_reg[4][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[4][5]/q U0_Register_File/Memory_reg[4][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[4][6]/q U0_Register_File/Memory_reg[4][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[4][7]/q U0_Register_File/Memory_reg[4][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[5][0]/q U0_Register_File/Memory_reg[5][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[5][1]/q U0_Register_File/Memory_reg[5][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[5][2]/q U0_Register_File/Memory_reg[5][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[5][3]/q U0_Register_File/Memory_reg[5][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[5][4]/q U0_Register_File/Memory_reg[5][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[5][5]/q U0_Register_File/Memory_reg[5][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[5][6]/q U0_Register_File/Memory_reg[5][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[5][7]/q U0_Register_File/Memory_reg[5][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[6][0]/q U0_Register_File/Memory_reg[6][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[6][1]/q U0_Register_File/Memory_reg[6][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[6][2]/q U0_Register_File/Memory_reg[6][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[6][3]/q U0_Register_File/Memory_reg[6][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[6][4]/q U0_Register_File/Memory_reg[6][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[6][5]/q U0_Register_File/Memory_reg[6][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[6][6]/q U0_Register_File/Memory_reg[6][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[6][7]/q U0_Register_File/Memory_reg[6][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[7][0]/q U0_Register_File/Memory_reg[7][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[7][1]/q U0_Register_File/Memory_reg[7][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[7][2]/q U0_Register_File/Memory_reg[7][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[7][3]/q U0_Register_File/Memory_reg[7][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[7][4]/q U0_Register_File/Memory_reg[7][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[7][5]/q U0_Register_File/Memory_reg[7][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[7][6]/q U0_Register_File/Memory_reg[7][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[7][7]/q U0_Register_File/Memory_reg[7][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[8][0]/q U0_Register_File/Memory_reg[8][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[8][1]/q U0_Register_File/Memory_reg[8][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[8][2]/q U0_Register_File/Memory_reg[8][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[8][3]/q U0_Register_File/Memory_reg[8][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[8][4]/q U0_Register_File/Memory_reg[8][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[8][5]/q U0_Register_File/Memory_reg[8][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[8][6]/q U0_Register_File/Memory_reg[8][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[8][7]/q U0_Register_File/Memory_reg[8][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[9][0]/q U0_Register_File/Memory_reg[9][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[9][1]/q U0_Register_File/Memory_reg[9][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[9][2]/q U0_Register_File/Memory_reg[9][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[9][3]/q U0_Register_File/Memory_reg[9][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[9][4]/q U0_Register_File/Memory_reg[9][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[9][5]/q U0_Register_File/Memory_reg[9][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[9][6]/q U0_Register_File/Memory_reg[9][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[9][7]/q U0_Register_File/Memory_reg[9][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[10][0]/q U0_Register_File/Memory_reg[10][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[10][1]/q U0_Register_File/Memory_reg[10][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[10][2]/q U0_Register_File/Memory_reg[10][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[10][3]/q U0_Register_File/Memory_reg[10][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[10][4]/q U0_Register_File/Memory_reg[10][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[10][5]/q U0_Register_File/Memory_reg[10][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[10][6]/q U0_Register_File/Memory_reg[10][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[10][7]/q U0_Register_File/Memory_reg[10][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[11][0]/q U0_Register_File/Memory_reg[11][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[11][1]/q U0_Register_File/Memory_reg[11][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[11][2]/q U0_Register_File/Memory_reg[11][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[11][3]/q U0_Register_File/Memory_reg[11][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[11][4]/q U0_Register_File/Memory_reg[11][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[11][5]/q U0_Register_File/Memory_reg[11][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[11][6]/q U0_Register_File/Memory_reg[11][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[11][7]/q U0_Register_File/Memory_reg[11][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[12][0]/q U0_Register_File/Memory_reg[12][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[12][1]/q U0_Register_File/Memory_reg[12][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[12][2]/q U0_Register_File/Memory_reg[12][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[12][3]/q U0_Register_File/Memory_reg[12][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[12][4]/q U0_Register_File/Memory_reg[12][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[12][5]/q U0_Register_File/Memory_reg[12][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[12][6]/q U0_Register_File/Memory_reg[12][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[12][7]/q U0_Register_File/Memory_reg[12][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[13][0]/q U0_Register_File/Memory_reg[13][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[13][1]/q U0_Register_File/Memory_reg[13][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[13][2]/q U0_Register_File/Memory_reg[13][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[13][3]/q U0_Register_File/Memory_reg[13][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[13][4]/q U0_Register_File/Memory_reg[13][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[13][5]/q U0_Register_File/Memory_reg[13][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[13][6]/q U0_Register_File/Memory_reg[13][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[13][7]/q U0_Register_File/Memory_reg[13][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[14][0]/q U0_Register_File/Memory_reg[14][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[14][1]/q U0_Register_File/Memory_reg[14][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[14][2]/q U0_Register_File/Memory_reg[14][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[14][3]/q U0_Register_File/Memory_reg[14][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[14][4]/q U0_Register_File/Memory_reg[14][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[14][5]/q U0_Register_File/Memory_reg[14][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[14][6]/q U0_Register_File/Memory_reg[14][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[14][7]/q U0_Register_File/Memory_reg[14][7]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[15][0]/q U0_Register_File/Memory_reg[15][0]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[15][1]/q U0_Register_File/Memory_reg[15][1]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[15][2]/q U0_Register_File/Memory_reg[15][2]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[15][3]/q U0_Register_File/Memory_reg[15][3]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[15][4]/q U0_Register_File/Memory_reg[15][4]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[15][5]/q U0_Register_File/Memory_reg[15][5]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[15][6]/q U0_Register_File/Memory_reg[15][6]/Q -type DFF DFF
add mapped point U0_Register_File/Memory[15][7]/q U0_Register_File/Memory_reg[15][7]/Q -type DFF DFF
add mapped point U0_Register_File/RdData_Valid/q U0_Register_File/RdData_Valid_reg/Q -type DFF DFF
add mapped point U0_Register_File/RdData[0]/q U0_Register_File/RdData_reg[0]/Q -type DFF DFF
add mapped point U0_Register_File/RdData[1]/q U0_Register_File/RdData_reg[1]/Q -type DFF DFF
add mapped point U0_Register_File/RdData[2]/q U0_Register_File/RdData_reg[2]/Q -type DFF DFF
add mapped point U0_Register_File/RdData[3]/q U0_Register_File/RdData_reg[3]/Q -type DFF DFF
add mapped point U0_Register_File/RdData[4]/q U0_Register_File/RdData_reg[4]/Q -type DFF DFF
add mapped point U0_Register_File/RdData[5]/q U0_Register_File/RdData_reg[5]/Q -type DFF DFF
add mapped point U0_Register_File/RdData[6]/q U0_Register_File/RdData_reg[6]/Q -type DFF DFF
add mapped point U0_Register_File/RdData[7]/q U0_Register_File/RdData_reg[7]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/current_state[0]/q U0_SYS_CTRL/current_state_reg[0]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/current_state[2]/q U0_SYS_CTRL/current_state_reg[2]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/current_state[1]/q U0_SYS_CTRL/current_state_reg[1]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[2]/q U0_SYS_CTRL/ALU_OUT_REG_reg[2]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[12]/q U0_SYS_CTRL/ALU_OUT_REG_reg[12]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[13]/q U0_SYS_CTRL/ALU_OUT_REG_reg[13]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[0]/q U0_SYS_CTRL/ALU_OUT_REG_reg[0]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[14]/q U0_SYS_CTRL/ALU_OUT_REG_reg[14]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[15]/q U0_SYS_CTRL/ALU_OUT_REG_reg[15]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[1]/q U0_SYS_CTRL/ALU_OUT_REG_reg[1]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[10]/q U0_SYS_CTRL/ALU_OUT_REG_reg[10]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[11]/q U0_SYS_CTRL/ALU_OUT_REG_reg[11]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[9]/q U0_SYS_CTRL/ALU_OUT_REG_reg[9]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[6]/q U0_SYS_CTRL/ALU_OUT_REG_reg[6]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[7]/q U0_SYS_CTRL/ALU_OUT_REG_reg[7]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[8]/q U0_SYS_CTRL/ALU_OUT_REG_reg[8]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[5]/q U0_SYS_CTRL/ALU_OUT_REG_reg[5]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[4]/q U0_SYS_CTRL/ALU_OUT_REG_reg[4]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ALU_OUT_REG[3]/q U0_SYS_CTRL/ALU_OUT_REG_reg[3]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/current_state[3]/q U0_SYS_CTRL/current_state_reg[3]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ADDR_REG[3]/q U0_SYS_CTRL/ADDR_REG_reg[3]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ADDR_REG[1]/q U0_SYS_CTRL/ADDR_REG_reg[1]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ADDR_REG[2]/q U0_SYS_CTRL/ADDR_REG_reg[2]/Q -type DFF DFF
add mapped point U0_SYS_CTRL/ADDR_REG[0]/q U0_SYS_CTRL/ADDR_REG_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_FSM/current_state[0]/q U0_UART/U0_UART_RX/U0_FSM/current_state_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_FSM/current_state[1]/q U0_UART/U0_UART_RX/U0_FSM/current_state_reg[1]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_FSM/current_state[2]/q U0_UART/U0_UART_RX/U0_FSM/current_state_reg[2]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_data_sampling/sampled_data[0]/q U0_UART/U0_UART_RX/U0_data_sampling/sampled_data_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_data_sampling/sampled_bit/q U0_UART/U0_UART_RX/U0_data_sampling/sampled_bit_reg/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_data_sampling/sampled_data[1]/q U0_UART/U0_UART_RX/U0_data_sampling/sampled_data_reg[1]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_data_sampling/sampled_data[2]/q U0_UART/U0_UART_RX/U0_data_sampling/sampled_data_reg[2]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_deserializer/P_DATA[2]/q U0_UART/U0_UART_RX/U0_deserializer/P_DATA_reg[2]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_deserializer/P_DATA[5]/q U0_UART/U0_UART_RX/U0_deserializer/P_DATA_reg[5]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_deserializer/P_DATA[6]/q U0_UART/U0_UART_RX/U0_deserializer/P_DATA_reg[6]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_deserializer/P_DATA[0]/q U0_UART/U0_UART_RX/U0_deserializer/P_DATA_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_deserializer/P_DATA[3]/q U0_UART/U0_UART_RX/U0_deserializer/P_DATA_reg[3]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_deserializer/P_DATA[4]/q U0_UART/U0_UART_RX/U0_deserializer/P_DATA_reg[4]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_deserializer/P_DATA[1]/q U0_UART/U0_UART_RX/U0_deserializer/P_DATA_reg[1]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_deserializer/P_DATA[7]/q U0_UART/U0_UART_RX/U0_deserializer/P_DATA_reg[7]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_edge_bit_counter/bit_cnt[3]/q U0_UART/U0_UART_RX/U0_edge_bit_counter/bit_cnt_reg[3]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_edge_bit_counter/bit_cnt[2]/q U0_UART/U0_UART_RX/U0_edge_bit_counter/bit_cnt_reg[2]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_edge_bit_counter/bit_cnt[1]/q U0_UART/U0_UART_RX/U0_edge_bit_counter/bit_cnt_reg[1]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_edge_bit_counter/bit_cnt[0]/q U0_UART/U0_UART_RX/U0_edge_bit_counter/bit_cnt_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt[3]/q U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt_reg[3]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt[2]/q U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt_reg[2]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt[1]/q U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt_reg[1]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt[4]/q U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt_reg[4]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt[0]/q U0_UART/U0_UART_RX/U0_edge_bit_counter/edge_cnt_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_parity_check/par_err/q U0_UART/U0_UART_RX/U0_parity_check/par_err_reg/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_parity_check/parity/q U0_UART/U0_UART_RX/U0_parity_check/parity_reg/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_stop_check/stp_err/q U0_UART/U0_UART_RX/U0_stop_check/stp_err_reg/Q -type DFF DFF
add mapped point U0_UART/U0_UART_RX/U0_strt_check/strt_glitch/q U0_UART/U0_UART_RX/U0_strt_check/strt_glitch_reg/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_FSM/current_state[0]/q U0_UART/U0_UART_TX/U0_FSM/current_state_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_FSM/current_state[2]/q U0_UART/U0_UART_TX/U0_FSM/current_state_reg[2]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_FSM/current_state[1]/q U0_UART/U0_UART_TX/U0_FSM/current_state_reg[1]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data[2]/q U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data_reg[2]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data[1]/q U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data_reg[1]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data[0]/q U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data[3]/q U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data_reg[3]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data[6]/q U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data_reg[6]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data[5]/q U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data_reg[5]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data[4]/q U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data_reg[4]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data[7]/q U0_UART/U0_UART_TX/U0_parity_Calc/parallel_data_reg[7]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/counter[3]/q U0_UART/U0_UART_TX/U0_serializer/counter_reg[3]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/ser_done/q U0_UART/U0_UART_TX/U0_serializer/ser_done_reg/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/counter[2]/q U0_UART/U0_UART_TX/U0_serializer/counter_reg[2]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/counter[1]/q U0_UART/U0_UART_TX/U0_serializer/counter_reg[1]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/parallel_data[3]/q U0_UART/U0_UART_TX/U0_serializer/parallel_data_reg[3]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/parallel_data[2]/q U0_UART/U0_UART_TX/U0_serializer/parallel_data_reg[2]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/parallel_data[1]/q U0_UART/U0_UART_TX/U0_serializer/parallel_data_reg[1]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/parallel_data[4]/q U0_UART/U0_UART_TX/U0_serializer/parallel_data_reg[4]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/parallel_data[0]/q U0_UART/U0_UART_TX/U0_serializer/parallel_data_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/parallel_data[6]/q U0_UART/U0_UART_TX/U0_serializer/parallel_data_reg[6]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/parallel_data[5]/q U0_UART/U0_UART_TX/U0_serializer/parallel_data_reg[5]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/counter[0]/q U0_UART/U0_UART_TX/U0_serializer/counter_reg[0]/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/S_DATA/q U0_UART/U0_UART_TX/U0_serializer/S_DATA_reg/Q -type DFF DFF
add mapped point U0_UART/U0_UART_TX/U0_serializer/parallel_data[7]/q U0_UART/U0_UART_TX/U0_serializer/parallel_data_reg[7]/Q -type DFF DFF
add mapped point U1_Integer_Clock_Divider_RX/counter[6]/q U1_Integer_Clock_Divider_RX/counter_reg[6]/Q -type DFF DFF
add mapped point U1_Integer_Clock_Divider_RX/counter[5]/q U1_Integer_Clock_Divider_RX/counter_reg[5]/Q -type DFF DFF
add mapped point U1_Integer_Clock_Divider_RX/counter[4]/q U1_Integer_Clock_Divider_RX/counter_reg[4]/Q -type DFF DFF
add mapped point U1_Integer_Clock_Divider_RX/gen_clk/q U1_Integer_Clock_Divider_RX/gen_clk_reg/Q -type DFF DFF
add mapped point U1_Integer_Clock_Divider_RX/counter[0]/q U1_Integer_Clock_Divider_RX/counter_reg[0]/Q -type DFF DFF
add mapped point U1_Integer_Clock_Divider_RX/counter[2]/q U1_Integer_Clock_Divider_RX/counter_reg[2]/Q -type DFF DFF
add mapped point U1_Integer_Clock_Divider_RX/counter[3]/q U1_Integer_Clock_Divider_RX/counter_reg[3]/Q -type DFF DFF
add mapped point U1_Integer_Clock_Divider_RX/counter[1]/q U1_Integer_Clock_Divider_RX/counter_reg[1]/Q -type DFF DFF
add mapped point U1_RST_SYNC_UART/sync_reg[1]/q U1_RST_SYNC_UART/sync_reg_reg[1]/Q -type DFF DFF
add mapped point U1_RST_SYNC_UART/sync_reg[0]/q U1_RST_SYNC_UART/sync_reg_reg[0]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
