tclmode

# Generated by Genus(TM) Synthesis Solution 25.10-p002_1, revision 1.578
# Generated on: Sat Jul 04 14:09:40 IST 2026 (Sat Jul 04 08:39:40 UTC 2026)

set_screen_display -noprogress
set_dofile_abort exit

### RTL names flow is enabled. ###
# Root attribute 'wlec_rtl_names_flow'        was 'true'.

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

set lec_version_required "19.10100"
if {$lec_version < $lec_version_required} {
    puts "// Error: Support for RTL names flow was added in LEC version 19.10-p100."
    puts "          A more recent version must be used."
    error ""
}

# Turns on the flowgraph datapath solver.
set wlec_analyze_dp_flowgraph true
# Indicates that resource sharing datapath optimization is present.
set share_dp_analysis         true

# The flowgraph solver is recommended for datapath analysis in LEC 19.1 or newer.
if {$wlec_analyze_dp_flowgraph} {
    set DATAPATH_SOLVER_OPTION "-flowgraph"
} elseif {$share_dp_analysis} {
    set DATAPATH_SOLVER_OPTION "-share"
} else {
    set DATAPATH_SOLVER_OPTION ""
}

tcl_set_command_name_echo on

set logfile fv/TOP/rtl_to_fv_map.log ;# user can modify this name for succeeding runs

set_log_file $logfile -replace

usage -auto -elapse

set_mapping_method -sensitive

set_verification_information rtl_fv_map_db

read_implementation_information fv/TOP -revised fv_map -use_rtl_names

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,4 -norelease_license
set_compare_options -threads 1,4

set env(RC_VERSION)     "25.10-p002_1"
set env(CDN_SYNTH_ROOT) "/mnt/22b703da-ca2b-42dd-9641-48ed3afe6614/cadence/installs/DDI251/GENUS251/tools.lnx86"
set CDN_SYNTH_ROOT      "/mnt/22b703da-ca2b-42dd-9641-48ed3afe6614/cadence/installs/DDI251/GENUS251/tools.lnx86"
set env(CW_DIR) "/mnt/22b703da-ca2b-42dd-9641-48ed3afe6614/cadence/installs/DDI251/GENUS251/tools.lnx86/lib/chipware"
set CW_DIR      "/mnt/22b703da-ca2b-42dd-9641-48ed3afe6614/cadence/installs/DDI251/GENUS251/tools.lnx86/lib/chipware"
set lec_version_required "21.20249"
if { ($lec_version < $lec_version_required) &&
    [file exists /mnt/22b703da-ca2b-42dd-9641-48ed3afe6614/cadence/installs/DDI251/GENUS251/tools.lnx86/lib/chipware/old_encrypt_sim]} {
    set env(CW_DIR_SIM) "/mnt/22b703da-ca2b-42dd-9641-48ed3afe6614/cadence/installs/DDI251/GENUS251/tools.lnx86/lib/chipware/old_encrypt_sim"
    set CW_DIR_SIM      "/mnt/22b703da-ca2b-42dd-9641-48ed3afe6614/cadence/installs/DDI251/GENUS251/tools.lnx86/lib/chipware/old_encrypt_sim"
} else {
    set env(CW_DIR_SIM) "/mnt/22b703da-ca2b-42dd-9641-48ed3afe6614/cadence/installs/DDI251/GENUS251/tools.lnx86/lib/chipware/sim"
    set CW_DIR_SIM      "/mnt/22b703da-ca2b-42dd-9641-48ed3afe6614/cadence/installs/DDI251/GENUS251/tools.lnx86/lib/chipware/sim"
}
set_multiplier_implementation boothrca -both

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

# ILM modules: 

add_search_path ../../Library/timing -library -both
read_library -liberty -both \
    /home/admin/DFT/SOCX/SCAN/../../Library/timing/slow.lib

set_undriven_signal 0 -golden
set_naming_style genus -golden
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden
set_naming_rule -ungroup_separator {_} -golden
set_naming_rule -ignore_case_gen_name

# Align LEC's treatment of mismatched port widths with constant
# connections with Genus's. Genus message CDFG-467 and LEC message
# HRC3.6 may indicate the presence of this issue.
set_hdl_options -const_port_extend
set_hdl_options -unsigned_conversion_overflow on
set_hdl_option -UNSIZED_CONSTANT_TRUNCATE off
set_hdl_option -v_to_vd on

# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
set_hdl_option -extract_macro_constraint
}
set lec_version_required "20.20226"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -VERILOG_INCLUDE_DIR "sep:src"
} else {
    set_hdl_options -VERILOG_INCLUDE_DIR "sep:src:cwd"
}
delete_search_path -all -design -golden
add_search_path ../RTL -design -golden
read_design -enumconstraint -define SYNTHESIS  -merge bbox -golden -lastmod -noelab  -sv09 ../RTL/Integer_Clock_Divider.sv ../RTL/SYS_CTRL.sv ../RTL/SYS_TOP.sv ../RTL/UART_RX_FSM.sv ../RTL/UART_TX.sv ../RTL/UART_TX_FSM.sv ../RTL/UART_TX_MUX.sv ../RTL/UART_TX_parity_Calc.sv ../RTL/UART_TX_serializer.sv
# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
set_hdl_option -extract_macro_constraint
}
delete_search_path -all -design -golden
add_search_path ../RTL -design -golden
read_design -enumconstraint -define SYNTHESIS  -merge bbox -golden -lastmod -noelab  -sv09 ../RTL/ALU_16B.v ../RTL/Async_fifo.v ../RTL/BIT_SYNC.v ../RTL/CLKDIV_MUX.v ../RTL/CLK_GATE.v ../RTL/DATA_SYNC.v ../RTL/PULSE_GEN.v ../RTL/RST_SYNC.v ../RTL/Register_File.v ../RTL/UART.v ../RTL/UART_RX.v ../RTL/UART_RX_data_sampling.v ../RTL/UART_RX_deserializer.v ../RTL/UART_RX_edge_bit_counter.v ../RTL/UART_RX_parity_check.v ../RTL/UART_RX_stop_check.v ../RTL/UART_RX_strt_check.v ../RTL/fifo_mem.v ../RTL/fifo_rd.v ../RTL/fifo_wr.v
elaborate_design -golden -root {TOP} -rootonly -rootonly  

read_design -verilog95   -revised -lastmod -noelab fv/TOP/fv_map.v.gz
elaborate_design -revised -root {TOP}

write_design -golden rtl_fv_map_db/elab.v -replace
uniquify -all -nolib -golden

report_design_data
report_black_box
report_modules

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -hier_seq_merge

set_flatten_model -balanced_modeling

puts "Dofile includes automatically generated DFT constraints. Carefully review the constraints"
puts "to ensure that functional logic is not excluded from verification."
puts "Use 'write_do_lec -no_dft' to comment out DFT constraints."
# Table of test_signals and related attributes
#
# Index  Pin                            Type             Dedicated  Has_fanout  Port/Pin    special test function      Dft_auto_created      User_defined  LEC_value                      
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
#  1      ScanEnable                     shift_enable     true       false       port        none                       true                  true          auto       
#  2      TestMode                       test_mode        true       false       port        none                       true                  true          auto       
#  3      RST_N                          test_mode        true       true        port        none                       false                 true          auto       
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
# Warning : Multiple pin constraints are added to the revised design.
#          The constraints needed to disable test mode are not trivial.
#          It is possible that some valid functional modes will be excluded
#          from the formal verification process.
#          Review the constraints to ensure they are all expected
#          and appropriate.
add_pin_constraints 1 {RST_N} -golden
add_ignored_outputs {ScanOut_1} -golden
add_ignored_outputs {ScanOut_2} -golden
add_ignored_outputs {ScanOut_3} -golden
add_ignored_outputs {ScanOut_4} -golden
add_ignored_outputs {ScanOut_5} -golden
add_ignored_outputs {ScanOut_6} -golden
add_ignored_outputs {ScanOut_7} -golden
add_ignored_outputs {ScanOut_8} -golden
add_ignored_outputs {ScanOut_9} -golden
add_ignored_outputs {ScanOut_10} -golden
add_ignored_outputs {ScanOut_11} -golden
add_ignored_outputs {ScanOut_12} -golden
add_ignored_outputs {ScanOut_13} -golden
add_ignored_outputs {ScanOut_14} -golden
add_ignored_outputs {ScanOut_15} -golden
add_ignored_outputs {ScanOut_16} -golden
add_ignored_outputs {ScanOut_17} -golden
add_ignored_outputs {ScanOut_18} -golden
add_ignored_outputs {ScanOut_19} -golden
add_ignored_outputs {ScanOut_20} -golden
add_pin_constraints 0 {ScanEnable} -revised
add_pin_constraints 0 {TestMode} -revised
add_pin_constraints 1 {RST_N} -revised
add_ignored_outputs {ScanOut_1} -revised
add_ignored_outputs {ScanOut_2} -revised
add_ignored_outputs {ScanOut_3} -revised
add_ignored_outputs {ScanOut_4} -revised
add_ignored_outputs {ScanOut_5} -revised
add_ignored_outputs {ScanOut_6} -revised
add_ignored_outputs {ScanOut_7} -revised
add_ignored_outputs {ScanOut_8} -revised
add_ignored_outputs {ScanOut_9} -revised
add_ignored_outputs {ScanOut_10} -revised
add_ignored_outputs {ScanOut_11} -revised
add_ignored_outputs {ScanOut_12} -revised
add_ignored_outputs {ScanOut_13} -revised
add_ignored_outputs {ScanOut_14} -revised
add_ignored_outputs {ScanOut_15} -revised
add_ignored_outputs {ScanOut_16} -revised
add_ignored_outputs {ScanOut_17} -revised
add_ignored_outputs {ScanOut_18} -revised
add_ignored_outputs {ScanOut_19} -revised
add_ignored_outputs {ScanOut_20} -revised

set lec_version_required "21.10142"
if {$lec_version >= $lec_version_required} {
    puts "For safety of verification, PIs and POs should be mapped by name."
    set_mapping_method -mapping_file_nopipo
}
set_mapping_method -search_in_mapping_file
set_analyze_option -mapping_file fv/TOP/fv_map.map.do
check_mapping_setup -mapping_file_quality -summary

# Reports the quality of the implementation information.
# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
    check_verification_information
}

set_analyze_option -auto -report_map

write_hier_compare_dofile hier_tmp1.lec.do -verbose -noexact_pin_match -replace -usage \
 -balanced_extraction -constraint -input_output_pin_equivalence \
-prepend_string "report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath $DATAPATH_SOLVER_OPTION -verbose"
run_hier_compare hier_tmp1.lec.do -dynamic_hierarchy

report_hier_compare_result -dynamicflattened

report_verification -hier -verbose

set_system_mode lec
write_compared_points noneq.compared_points.TOP.rtl.fv_map.tcl -class noneq -tclmode -replace
set lec_version_required "21.10100"
if {$lec_version >= $lec_version_required} {
    analyze_nonequivalent -source_diagnosis
    report_nonequivalent_analysis > noneq.source_diag.TOP.rtl.fv_map.rpt
}
report_test_vector -noneq > noneq.test_vector.TOP.rtl.fv_map.rpt
set_system_mode setup
write_verification_information
report_verification_information

# Reports how effective the implementation information was.
report_implementation_information

set_system_mode lec

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
analyze_results -logfiles $logfile

vpxmode

exit -f
