 
# 
 
#  Generated by Genus(TM) Synthesis Solution 25.10-p002_1
 
# Modus ATPG Script
 
#-------------------------------------------------------------------------------
# INITIALIZE VARIABLES
#-------------------------------------------------------------------------------
# "set_db workdir" is recommended to be set first to initialize where the Database is to be located
# WORKDIR Tcl variable can be used in the script to reference file locations
set_db workdir TOP_TP;
set   WORKDIR [get_db workdir]
 
# Configure the database
set_option stdout     all;                                     # Not printing output for each command to the terminal
                                                          # Logs contain the complete command output
set ::env(CDS_LIC_REPORT) yes
set_db stop_on_severity error;
 
file delete -force $WORKDIR/tbdata;                       # Delete Test Database
file delete -force $WORKDIR/testresults;                  # Delete Test Output Files/Logs
 
 
 
#-------------------------------------------------------------------------------
# BUILD THE LOGIC MODEL
#-------------------------------------------------------------------------------
build_model \
    -cell	 TOP \
    -techlib	 ../../../Library/verilog/typical.v \
    -designsource	 $WORKDIR/test_netlist.v \
    -allowmissingmodules	 yes \
    -messagecounteach	 100 \

 
#-------------------------------------------------------------------------------
# BUILD THE TEST MODEL
#-------------------------------------------------------------------------------
build_testmode \
    -testmode	 SCAN \
    -assignfile	 $WORKDIR/test.pinassign \
    -modedef	 test.modedef \
    -modedefpath	 $WORKDIR \
 
 
#-------------------------------------------------------------------------------
# BUILD THE FAULT MODEL
#-------------------------------------------------------------------------------
build_faultmodel \
    -includedynamic	 no \
 
 
