 
# 
 
#  Generated by Genus(TM) Synthesis Solution 25.10-p002_1
 
# Modus ATPG Script
 
#-------------------------------------------------------------------------------
# INITIALIZE VARIABLES
#-------------------------------------------------------------------------------
# "set_db workdir" is recommended to be set first to initialize where the Database is to be located
# WORKDIR Tcl variable can be used in the script to reference file locations
set_db workdir TOP_TP;
set   WORKDIR [get_db workdir]
 
# Configure the database
set_option stdout     all;                                     # Not printing output for each command to the terminal
                                                          # Logs contain the complete command output
set ::env(CDS_LIC_REPORT) yes
set_db stop_on_severity error;
 
#-------------------------------------------------------------------------------
# VERIFY THE TEST MODEL
#-------------------------------------------------------------------------------
verify_test_structures \
    -testmode	 SCAN \
 
 
#-------------------------------------------------------------------------------
# ANALYZE FAULTS FOR TESTABILITY
#-------------------------------------------------------------------------------
analyze_testability \
    -testmode	 SCAN \
  -faultsample 20 \


